# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on:  windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Setup Java SDK
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft' 
        java-version: 17

      
    - name: Setup NuGet.exe for use with actions
        # You may pin to the exact commit or the version.
        # uses: NuGet/setup-nuget@fd9fffd6ca4541cf4152a9565835ca1a88a6eb37
      uses: NuGet/setup-nuget@v1.1.1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: search workloads
      run: dotnet workload search
    - name: restore workloads
      run: dotnet workload install maui maui-android maui-ios maui-maccatalyst maui-windows android --source https://api.nuget.org/v3/index.json
    - name: list workloads
      run: dotnet workload list

    - name: Restore nuget packages
      run:  msbuild src\caliburn.micro.sln -t:restore

    - name: Build app for release
      run: msbuild src\caliburn.micro.sln /t:Build 
    - name: Dotnet Tests
      uses: EasyDesk/action-dotnet-test@v1.0.0
      with:
        # (Optional) The root where the 'dotnet test' command should look for a project or a solution.
        # If not specified, defaults to the current directory.
        path: src\caliburn.micro.sln
        # (Optional) Additional command line arguments to be passed to 'dotnet test'.
        # Emtpy by default.
        # test-args: '<additional-test-args>'


        # (Optional) Whether to skip the build using the '--no-build' flag.
        # If not specified, defaults to true.
        skip-build: true


